### ISSUE TITLE
Docs: Add detailed instructions on how to configure a GitHub Copilot extension

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/copilot-extension-template#16]
I wrote a very detailed blog post on how to create and configure a GitHub Copilot extension in https://dev.to/nickytonline/creating-your-first-github-copilot-extension-a-step-by-step-guide-28g0.

It's a good blog post, but if people are to use this template, the steps for configuring the GitHub app, as well as your environment for development should be in the README, or more ideally, a separate markdown linked in the README. It should also include any images related to those things from the blog post.

The only thing to really omit is the steps for building the code as that is what this template project is.

**Comment by michaella23** [comment]
I'd like to give this a shot @nickytonline. :)

**Comment by nickytonline** [comment]
Awesome @michaella23! Let me know if you have any questions.

**Comment by michaella23** [comment]
> The only thing to really omit is the steps for building the code as that is what this template project is.

Can I get clarification on this @nickytonline ? Am I understanding correctly that the steps for building the code are in the first few sections of the article, and that's what I would omit?

Thanks!

**Comment by nickytonline** [comment]
> > The only thing to really omit is the steps for building the code as that is what this template project is.
> 
> 
> 
> Can I get clarification on this @nickytonline ? Am I understanding correctly that the steps for building the code are in the first few sections of the article, and that's what I would omit?
> 
> 
> 
> Thanks!
> 
> 
> 
> 

Exactly because the template is that code I walk you through. How to configure the GitHub app and how to set up the development environment are the main pieces to bring in.
